Repository Piotr-Glab495/SportEventManager, pull requests merged in 2023-06, with the labels that each got.

#34 Feature/sem 5 team manager without crashing
  src/SportEventManager.Core/TeamAggregate/Player.cs
  src/SportEventManager.Core/TeamAggregate/Specifications/TeamByIdWithPlayersSpec.cs
  src/SportEventManager.Core/TeamAggregate/Specifications/TeamsByOwnerIdSpec.cs
  src/SportEventManager.Core/TeamAggregate/Specifications/TeamsWithPlayersByOwnerIdSpec.cs
  src/SportEventManager.Core/TeamAggregate/Specifications/TeamsWithPlayersSpec.cs
  src/SportEventManager.Core/TeamAggregate/Team.cs
  src/SportEventManager.Core/TeamAggregate/TeamPlayer.cs
  src/SportEventManager.Infrastructure/Data/AppDbContext.cs
  src/SportEventManager.Infrastructure/Migrations/AppDb/AppDbContextModelSnapshot.cs
  src/SportEventManager.Web/Controllers/TeamManagerController.cs
  src/SportEventManager.Web/ViewModels/TeamModel/PlayerViewModel.cs
  src/SportEventManager.Web/ViewModels/TeamModel/TeamPlayerViewModel.cs
  src/SportEventManager.Web/ViewModels/TeamModel/TeamViewModel.cs
  src/SportEventManager.Web/Views/EventManager/Create.cshtml
  src/SportEventManager.Web/Views/EventManager/Details.cshtml
  src/SportEventManager.Web/Views/TeamManager/Create.cshtml
  src/SportEventManager.Web/Views/TeamManager/Details.cshtml
  src/SportEventManager.Web/Views/TeamManager/Edit.cshtml
  src/SportEventManager.Web/Views/TeamManager/Index.cshtml
  src/SportEventManager.Web/wwwroot/js/EventManager/Create.js
  src/SportEventManager.Web/wwwroot/js/TeamManager/CreateEdit.js
  src/SportEventManager.Web/wwwroot/js/site.js
Labels: enhancement

#38 SEM-8 Bump safe packages from dependabot PRs
  Directory.Packages.props
Labels: dependencies

#39 SEM-8 Bump safe packages from dependabot PRs
  Directory.Packages.props
Labels: dependencies

#41 SEM-9 Fix for user Id recognition in EventManager module
  src/SportEventManager.Web/Controllers/EventManagerController.cs
Labels: bugfix

#59 Added the ability to complete players statistics.
  src/SportEventManager.Core/EventAggregate/Event.cs
  src/SportEventManager.Core/EventAggregate/Match.cs
  src/SportEventManager.Core/EventAggregate/Specifications/EventByIdWithTeamsAndStadiumsSpec.cs
  src/SportEventManager.Core/EventAggregate/Specifications/EventsByIdWithItemsSpec.cs
  src/SportEventManager.Core/StatisticsAggregate/FbPlayerMatchStats.cs
  src/SportEventManager.Core/StatisticsAggregate/FbTeamMatchStats.cs
  src/SportEventManager.Web/Controllers/EventManagerController.cs
  src/SportEventManager.Web/Controllers/EventViewController.cs
  src/SportEventManager.Web/ViewModels/EventModel/MatchViewModel.cs
  src/SportEventManager.Web/ViewModels/TeamModel/Stats/FbPlayerMatchStatsViewModel.cs
  src/SportEventManager.Web/Views/EventView/ShowMatches.cshtml
  src/SportEventManager.Web/Views/EventView/Stats.cshtml
  src/SportEventManager.Web/wwwroot/css/EventView/Matches.css
Labels: enhancement

#55 Update TeamManager
  src/SportEventManager.Core/TeamAggregate/Team.cs
  src/SportEventManager.Web/Controllers/TeamManagerController.cs
  src/SportEventManager.Web/ViewModels/TeamModel/TeamViewModel.cs
  src/SportEventManager.Web/Views/TeamManager/Create.cshtml
Labels: enhancement

#63 Feature/sem 5 team manager without crashing dev conflict
  src/SportEventManager.Core/TeamAggregate/Team.cs
  src/SportEventManager.Web/Controllers/TeamManagerController.cs
  src/SportEventManager.Web/SeedData.cs
  src/SportEventManager.Web/ViewModels/TeamModel/TeamViewModel.cs
  src/SportEventManager.Web/Views/TeamManager/Create.cshtml
Labels: enhancement

#65 Feature/sem 2 refactoring database and front accordingly dev conflict
  src/SportEventManager.Web/Views/EventManager/Index.cshtml
Labels: bugfix

#66 Start work on tournament bracket.
  src/SportEventManager.Core/EventAggregate/Specifications/EventsByIdWithItemsSpec.cs
  src/SportEventManager.Web/SportEventManager.Web.csproj
  src/SportEventManager.Web/ViewModels/EventModel/MatchViewModel.cs
  src/SportEventManager.Web/ViewModels/TeamModel/Stats/FbPlayerMatchStatsViewModel.cs
  src/SportEventManager.Web/Views/EventView/ShowMatches.cshtml
  src/SportEventManager.Web/Views/EventView/Stats.cshtml
  src/SportEventManager.Web/Views/Shared/_Layout.cshtml
  src/SportEventManager.Web/compilerconfig.json
  src/SportEventManager.Web/compilerconfig.json.defaults
  src/SportEventManager.Web/wwwroot/css/EventView/Bracket.css
  src/SportEventManager.Web/wwwroot/css/EventView/Bracket.less
  src/SportEventManager.Web/wwwroot/css/EventView/Bracket.min.css
  src/SportEventManager.Web/wwwroot/css/EventView/Matches.css
Labels: bugfix
